POSIX updates

diff --git a/quick-back b/quick-back
--- a/quick-back
+++ b/quick-back
@@ -63,7 +63,7 @@ fi
 while [ "$EXCLUDESNUM" -ge 1 ]; do #LIFO queue
 	CMD="${CMD} --exclude="
     	CMD="${CMD}${EXCLUDEDIR[$EXCLUDESNUM]}"
-	EXCLUDESNUM=$(expr $EXCLUDESNUM - 1)
+	EXCLUDESNUM=$(($EXCLUDESNUM - 1))
 done
   
 #run the job
@@ -76,7 +76,7 @@ backup_boot ()
 #if /boot exists on the source then
 if [ -d "$SRC"/boot ]; then
 #run rsync to copy the initramfs and kernel to the backup
-if ! rsync $OPTIONS --delete "$SRC"/boot/*vmlinuz* "$DEST_PATH"/boot/; then
+if ! rsync "$OPTIONS" --delete "$SRC"/boot/*vmlinuz* "$DEST_PATH"/boot/; then
 	echo "failed to backup the kernel"
 	echo "does it not exist?"
 fi
@@ -329,7 +329,7 @@ while [ "$1" != "" ]; do
 								;;
 		-v | --verbose )        OPTIONS="${OPTIONS} -v"
                                 ;;
-        * )                     echo "invalid option "$1""
+        * )                     echo "invalid option \"$1\""
                                 usage
                                 exit 1
     esac
